import React, { useState } from "react";
import { T, btn, lbl } from "../theme.js";
import { VENUE, PLACES } from "../data/venue.js";
import { askClaude } from "../lib/ai.js";
import { Eyebrow, Panel, Spinner } from "./ui.jsx";

/**
 * AI wayfinding surface: plans routes between venue points with an optional
 * hard step-free constraint, using live gate-queue data for crowd avoidance.
 * @param {{gates: Array<{id: string, queueMin: number}>}} props
 */
export default function Navigate({ gates }) {
  const [from, setFrom] = useState("Gate 2");
  const [to, setTo] = useState("Sector G");
  const [stepFree, setStepFree] = useState(false);
  const [route, setRoute] = useState(null);
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState("");

  const go = async () => {
    setBusy(true); setErr(""); setRoute(null);
    try {
      const result = await askClaude(
        "route",
        [{
          role: "user",
          content:
            `Plan a walking route inside ${VENUE.name} from "${from}" to "${to}".` +
            (stepFree ? " The route MUST be fully step-free (elevators/ramps only, no stairs)." : "") +
            ` Venue layout facts: sectors A–H run clockwise around the bowl; gates and what they serve: ${JSON.stringify(VENUE.gates.map(g => ({ id: g.id, serves: g.serves })))}; ` +
            `step-free infrastructure: ${VENUE.stepFreePaths}; current gate queues (minutes): ${JSON.stringify(Object.fromEntries(gates.map(g => [g.id, g.queueMin])))}. ` +
            `Return ONLY JSON, no markdown: {"etaMin": number, "stepFree": boolean, "steps": ["short instruction", ...], "tip": "one crowd-avoidance or timing tip based on the queue data"}. 3–6 steps.`,
        }],
        "You are an indoor wayfinding AI for a stadium. Respond only with valid JSON.",
        true
      );
      setRoute(result);
    } catch {
      setErr("Couldn't plan that route. Try again.");
    }
    setBusy(false);
  };

  const selStyle = {
    background: T.panelHi, border: `1px solid ${T.line}`, borderRadius: 8,
    padding: "9px 10px", color: T.chalk, fontSize: 14, fontFamily: T.sans, width: "100%",
  };

  return (
    <div style={{ display: "grid", gridTemplateColumns: "minmax(0,1fr) minmax(0,1.2fr)", gap: 16 }} className="mdc-grid">
      <Panel>
        <Eyebrow color={T.amber}>Plan a route</Eyebrow>
        <label style={lbl()} htmlFor="nav-from">From</label>
        <select id="nav-from" value={from} onChange={(e) => setFrom(e.target.value)} style={{ ...selStyle, marginBottom: 12 }}>
          {PLACES.map((p) => <option key={p}>{p}</option>)}
        </select>
        <label style={lbl()} htmlFor="nav-to">To</label>
        <select id="nav-to" value={to} onChange={(e) => setTo(e.target.value)} style={selStyle}>
          {PLACES.map((p) => <option key={p}>{p}</option>)}
        </select>
        <label style={{ display: "flex", alignItems: "center", gap: 8, margin: "14px 0", fontSize: 14, cursor: "pointer" }}>
          <input type="checkbox" checked={stepFree} onChange={(e) => setStepFree(e.target.checked)} />
          Step-free route (no stairs)
        </label>
        <button onClick={go} disabled={busy} style={{ ...btn(T.amber), width: "100%" }}>
          {busy ? <>Routing <Spinner /></> : "Get directions"}
        </button>
        {err && <div style={{ color: T.red, fontSize: 13, marginTop: 10 }} role="alert">{err}</div>}
      </Panel>

      <Panel>
        <Eyebrow>Directions</Eyebrow>
        {!route && !busy && (
          <p style={{ color: T.dim, fontSize: 13 }}>
            Routes are generated by Claude from the venue layout and live queue data — it avoids congested gates and can keep the whole path step-free.
          </p>
        )}
        {route && (
          <div>
            <div style={{ display: "flex", gap: 10, marginBottom: 12, fontFamily: T.mono, fontSize: 12 }}>
              <span style={{ padding: "3px 10px", borderRadius: 999, background: T.panelHi, color: T.chalk }}>~{route.etaMin} min</span>
              {route.stepFree && <span style={{ padding: "3px 10px", borderRadius: 999, background: T.panelHi, color: T.green }}>step-free ✓</span>}
            </div>
            <ol style={{ margin: 0, paddingLeft: 20, display: "flex", flexDirection: "column", gap: 8 }}>
              {(route.steps || []).map((s, i) => (
                <li key={i} style={{ fontSize: 14, lineHeight: 1.5 }}>{s}</li>
              ))}
            </ol>
            {route.tip && (
              <div style={{ marginTop: 14, padding: 10, background: T.panelHi, borderRadius: 8, fontSize: 13, color: T.amber }}>
                ⚡ {route.tip}
              </div>
            )}
          </div>
        )}
      </Panel>
    </div>
  );
}
